### ISSUE TITLE
Allow deliverers to filter by delivery date

### ISSUE THREAD

**Issue by ryanwilsonperkin** [The-Peoples-Pantry/website#483]
Chefs set the delivery date for a given meal, allow deliverers to filter by these dates on the signup page so that they can see just those deliveries for a day that they're available for.

**Comment by samihibrahim** [comment]
I must be misunderstanding something 😅 because deliverers can now filter by delivery dates in their sign up page
![delivery_dates_filter](https://user-images.githubusercontent.com/559181/133897356-6476b8d7-8b1d-4925-a2fc-08d31ddf218a.png)

**Comment by ryanwilsonperkin** [comment]
Thanks @samihibrahim, looks like this issue is out of date, this was done back in https://github.com/The-Peoples-Pantry/website/pull/427
