### ISSUE TITLE
Support searching meal & grocery requests by ID

### ISSUE THREAD

**Issue by ryanwilsonperkin** [The-Peoples-Pantry/website#487]
Organizers would like to be able to search meal requests and grocery requests by ID in the search bar, Django supports this type of thing with `ModelAdmin#search_fields`

**Comment by tibet5** [comment]
Hi i would like to work on this.

**Comment by tibet5** [comment]
I am sorry i couldnt understand the issue i guess and couldnt create any meal or grocery request because it wants Canada zip code, i looked and tried but couldnt made it. So can give me more explanation on issue and some dummy data?

**Comment by ryanwilsonperkin** [comment]
Yeah requests are validated to require a postal code within Toronto, try setting it to M5V 3L9

**Comment by tibet5** [comment]
Hi i made the enhancement by adding 'id' in the search field and adding a equal prefix to the head '=id' like this also added that prefix to the phone_number field. It gives me correct result except the '2' value on the query i added the screenshot about the results do you have any idea why it returns more than one result in just '2'?
![search-query-result](https://user-images.githubusercontent.com/59174238/132812397-33c44bba-cbc4-4076-869d-3d9b9f287552.jpg)

**Comment by ryanwilsonperkin** [comment]
Nice work! It's not clear to me from the screenshot why it would be finding all of those others, by any chance does the email you used for them contain a 2 in it? That could have the effect, since the search field also searches emails.

One way to test would be to keep your existing data but check out the main branch (without your code changes), and try the search again. If it still selects those others, it's unrelated to the ID field that you've added.

**Comment by tibet5** [comment]
It was all e-mail... my e-mail contains '2' so it works well now

**Comment by tibet5** [comment]
Should i open a pull request it says able to merge? And a linked the issue in the commit

**Comment by ryanwilsonperkin** [comment]
Yep! Please open a Pull Request against this repository and I can review it for you 👍🏻
